run:
  go: "1.22"

linters:
  enable-all: true
  disable:
    # deprecated linter
    - execinquery
    - gomnd

linters-settings:
  goimports:
    local-prefixes: github.com/paulvollmer/go-genbuilder
  varnamelen:
    ignore-names:
      - err
      - tt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
