# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: example-mod-proxy
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
