package main

import (
	"go/ast"
	"go/token"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_generate(t *testing.T) {
	genConfig := &GeneratorConfig{
		PackageName: "testpackage",
		StructName:  "TestStruct",
		Imports: []Import{
			{Name: "sample1", Path: "sample1"},
			{Name: "customalias", Path: "sample2"},
		},
		Fields: []Field{
			{
				Name: "TestField",
				Type: "testType",
			},
			{
				Name: "testOtherField",
				Type: "int",
			},
		},
		BuildTags: []string{
			"//go:build example",
			"// +build example",
		},
	}

	result, err := generate(genConfig)
	assert.NoError(t, err)

	expected := `// Code generated by go-genbuilder. DO NOT EDIT.
//go:build example
// +build example

package testpackage

import (
	"sample1"
	customalias "sample2"
)

type TestStructBuilder struct {
	teststruct *TestStruct
}

func NewTestStructBuilder() *TestStructBuilder {
	return &TestStructBuilder{
		teststruct: &TestStruct{},
	}
}

func (builder *TestStructBuilder) SetTestField(testfield testType) *TestStructBuilder {
	builder.teststruct.TestField = testfield
	return builder
}

func (builder *TestStructBuilder) SetTestOtherField(testotherfield int) *TestStructBuilder {
	builder.teststruct.testOtherField = testotherfield
	return builder
}

func (builder *TestStructBuilder) Build() *TestStruct {
	return builder.teststruct
}
`

	assert.Equal(t, expected, string(result))
}

func TestParseFile(t *testing.T) {
	testcases := []struct {
		name             string
		input            string
		targetStructName string
		targetLine       int
	}{
		{
			name:             "using targetStructName",
			input:            "./example/main.go",
			targetStructName: "Shape2D",
			targetLine:       -1,
		},
		{
			name:             "using targetLine",
			input:            "./example/main.go",
			targetStructName: "",
			targetLine:       16,
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {

			actual, err := ParseFile(testcase.input, testcase.targetStructName, testcase.targetLine)
			assert.NoError(t, err)

			expected := &GeneratorConfig{
				PackageName: "main",
				StructName:  "Shape2D",
				Imports: []Import{
					{Name: "zap", Path: "go.uber.org/zap"},
				},
				Fields: []Field{
					{
						Name: "logger",
						Type: "zap.Logger",
					},
					{
						Name: "Kind",
						Type: "ShapeKind",
					},
					{
						Name: "X",
						Type: "int",
					},
					{
						Name: "Y",
						Type: "int",
					},
				},
				BuildTags: []string{
					"//go:build example",
					"// +build example",
				},
			}
			assert.Equal(t, expected, actual)
		})
	}
}

func Test_findImports(t *testing.T) {
	testcases := []struct {
		name     string
		file     *ast.File
		expected map[string]Import
	}{
		{
			name: "simple import",
			file: &ast.File{
				Decls: []ast.Decl{
					&ast.GenDecl{
						Tok: token.IMPORT,
						Specs: []ast.Spec{
							&ast.ImportSpec{
								Name: nil,
								Path: &ast.BasicLit{Kind: token.STRING, Value: `"fmt"`},
							},
							&ast.ImportSpec{
								Name: nil,
								Path: &ast.BasicLit{Kind: token.STRING, Value: `"go.uber.org/zap"`},
							},
						},
					},
				},
			},
			expected: map[string]Import{
				"fmt": {Name: "fmt", Path: "fmt"},
				"zap": {Name: "zap", Path: "go.uber.org/zap"},
			},
		},
		{
			name: "import with name",
			file: &ast.File{
				Decls: []ast.Decl{
					&ast.GenDecl{
						Tok: token.IMPORT,
						Specs: []ast.Spec{
							&ast.ImportSpec{
								Name: nil,
								Path: &ast.BasicLit{Kind: token.STRING, Value: "fmt"},
							},
							&ast.ImportSpec{
								Name: &ast.Ident{Name: "thezap"},
								Path: &ast.BasicLit{Kind: token.STRING, Value: "go.uber.org/zap"},
							},
						},
					},
				},
			},
			expected: map[string]Import{
				"fmt":    {Name: "fmt", Path: "fmt"},
				"thezap": {Name: "thezap", Path: "go.uber.org/zap"},
			},
		},
	}

	for _, testcase := range testcases {
		testcase := testcase
		t.Run(testcase.name, func(t *testing.T) {
			result := findImports(testcase.file)
			assert.Equal(t, testcase.expected, result)
		})
	}
}
