package main

import (
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_IgnoreFields_Ignore(t *testing.T) {
	t.Parallel()

	ignoreFields := IgnoreFields{
		"test": true,
	}

	assert.True(t, ignoreFields.Ignore("test"))
	assert.False(t, ignoreFields.Ignore("foo"))
}

func Test_generate(t *testing.T) {
	t.Parallel()

	testcases := []struct {
		testDescription string
		input           *GeneratorConfig
		expected        string
	}{
		{
			testDescription: "simple",
			input: &GeneratorConfig{
				Version:     "0.0.0",
				PackageName: "testpackage",
				StructName:  "TestStruct",
				Imports:     nil,
				Fields: []Field{
					{
						Name: "TestField",
						Type: "testType",
					},
				},
				BuildTags: nil,
			},
			expected: `// Code generated by go-genbuilder v0.0.0. DO NOT EDIT.

package testpackage

type TestStructBuilder struct {
	teststruct *TestStruct
}

// NewTestStructBuilder returns a builder for TestStruct.
func NewTestStructBuilder() *TestStructBuilder {
	return &TestStructBuilder{
		teststruct: &TestStruct{},
	}
}

// SetTestField sets TestField and returns the builder.
func (builder *TestStructBuilder) SetTestField(testfield testType) *TestStructBuilder {
	builder.teststruct.TestField = testfield
	return builder
}

// Build returns the built TestStruct.
func (builder *TestStructBuilder) Build() *TestStruct {
	return builder.teststruct
}
`,
		},
		{
			testDescription: "with imports and build tags",
			input: &GeneratorConfig{
				Version:     "0.0.0",
				PackageName: "testpackage",
				StructName:  "TestStruct",
				Imports: []Import{
					{Name: "context", Path: "context"},
					{Name: "sample1", Path: "sample1"},
					{Name: "customalias", Path: "sample2"},
				},
				Fields: []Field{
					{
						Name: "TestField",
						Type: "testType",
					},
					{
						Name: "testOtherField",
						Type: "int",
					},
					{
						Name: "testFunc",
						Type: "func(ctx context.Context)",
					},
				},
				BuildTags: []string{
					"//go:build example",
					"// +build example",
				},
			},
			expected: `// Code generated by go-genbuilder v0.0.0. DO NOT EDIT.
//go:build example
// +build example

package testpackage

import (
	"context"
	"sample1"
	customalias "sample2"
)

type TestStructBuilder struct {
	teststruct *TestStruct
}

// NewTestStructBuilder returns a builder for TestStruct.
func NewTestStructBuilder() *TestStructBuilder {
	return &TestStructBuilder{
		teststruct: &TestStruct{},
	}
}

// SetTestField sets TestField and returns the builder.
func (builder *TestStructBuilder) SetTestField(testfield testType) *TestStructBuilder {
	builder.teststruct.TestField = testfield
	return builder
}

// SetTestOtherField sets testOtherField and returns the builder.
func (builder *TestStructBuilder) SetTestOtherField(testotherfield int) *TestStructBuilder {
	builder.teststruct.testOtherField = testotherfield
	return builder
}

// SetTestFunc sets testFunc and returns the builder.
func (builder *TestStructBuilder) SetTestFunc(testfunc func(ctx context.Context)) *TestStructBuilder {
	builder.teststruct.testFunc = testfunc
	return builder
}

// Build returns the built TestStruct.
func (builder *TestStructBuilder) Build() *TestStruct {
	return builder.teststruct
}
`,
		},
		{
			testDescription: "field name lowercases to a keyword",
			input: &GeneratorConfig{
				Version:     "0.0.0",
				PackageName: "testpackage",
				StructName:  "TestStruct",
				Imports:     nil,
				Fields: []Field{
					{
						Name: "Type",
						Type: "string",
					},
					{
						Name: "Func",
						Type: "int",
					},
				},
				BuildTags: nil,
			},
			expected: `// Code generated by go-genbuilder v0.0.0. DO NOT EDIT.

package testpackage

type TestStructBuilder struct {
	teststruct *TestStruct
}

// NewTestStructBuilder returns a builder for TestStruct.
func NewTestStructBuilder() *TestStructBuilder {
	return &TestStructBuilder{
		teststruct: &TestStruct{},
	}
}

// SetType sets Type and returns the builder.
func (builder *TestStructBuilder) SetType(typeArg string) *TestStructBuilder {
	builder.teststruct.Type = typeArg
	return builder
}

// SetFunc sets Func and returns the builder.
func (builder *TestStructBuilder) SetFunc(funcArg int) *TestStructBuilder {
	builder.teststruct.Func = funcArg
	return builder
}

// Build returns the built TestStruct.
func (builder *TestStructBuilder) Build() *TestStruct {
	return builder.teststruct
}
`,
		},
		{
			testDescription: "receiver clash, case-distinct names, and blank field",
			input: &GeneratorConfig{
				Version:     "0.0.0",
				PackageName: "testpackage",
				StructName:  "TestStruct",
				Imports:     nil,
				Fields: []Field{
					{Name: "Builder", Type: "string"},
					{Name: "Foo", Type: "int"},
					{Name: "foo", Type: "int"},
					{Name: "Foo_bar", Type: "int"},
					{Name: "foo_bar", Type: "int"},
					{Name: "_", Type: "string"},
				},
				BuildTags: nil,
			},
			expected: `// Code generated by go-genbuilder v0.0.0. DO NOT EDIT.

package testpackage

type TestStructBuilder struct {
	teststruct *TestStruct
}

// NewTestStructBuilder returns a builder for TestStruct.
func NewTestStructBuilder() *TestStructBuilder {
	return &TestStructBuilder{
		teststruct: &TestStruct{},
	}
}

// SetBuilder sets Builder and returns the builder.
func (builder *TestStructBuilder) SetBuilder(builderArg string) *TestStructBuilder {
	builder.teststruct.Builder = builderArg
	return builder
}

// SetFoo sets Foo and returns the builder.
func (builder *TestStructBuilder) SetFoo(foo int) *TestStructBuilder {
	builder.teststruct.Foo = foo
	return builder
}

// Setfoo sets foo and returns the builder.
func (builder *TestStructBuilder) Setfoo(foo int) *TestStructBuilder {
	builder.teststruct.foo = foo
	return builder
}

// SetFoo_bar sets Foo_bar and returns the builder.
func (builder *TestStructBuilder) SetFoo_bar(foo_bar int) *TestStructBuilder {
	builder.teststruct.Foo_bar = foo_bar
	return builder
}

// Setfoo_bar sets foo_bar and returns the builder.
func (builder *TestStructBuilder) Setfoo_bar(foo_bar int) *TestStructBuilder {
	builder.teststruct.foo_bar = foo_bar
	return builder
}

// Build returns the built TestStruct.
func (builder *TestStructBuilder) Build() *TestStruct {
	return builder.teststruct
}
`,
		},
		{
			testDescription: "struct named Builder keeps the builder field",
			input: &GeneratorConfig{
				Version:     "0.0.0",
				PackageName: "testpackage",
				StructName:  "Builder",
				Imports:     nil,
				Fields: []Field{
					{Name: "X", Type: "int"},
				},
				BuildTags: nil,
			},
			expected: `// Code generated by go-genbuilder v0.0.0. DO NOT EDIT.

package testpackage

type BuilderBuilder struct {
	builder *Builder
}

// NewBuilderBuilder returns a builder for Builder.
func NewBuilderBuilder() *BuilderBuilder {
	return &BuilderBuilder{
		builder: &Builder{},
	}
}

// SetX sets X and returns the builder.
func (builder *BuilderBuilder) SetX(x int) *BuilderBuilder {
	builder.builder.X = x
	return builder
}

// Build returns the built Builder.
func (builder *BuilderBuilder) Build() *Builder {
	return builder.builder
}
`,
		},
	}

	for _, testcase := range testcases {
		testcase := testcase
		t.Run(testcase.testDescription, func(t *testing.T) {
			t.Parallel()

			result, err := generate(testcase.input)
			require.NoError(t, err)
			assert.Equal(t, testcase.expected, string(result))
		})
	}
}

func TestParseFile(t *testing.T) {
	t.Parallel()

	SetVersion("test")

	testcases := []struct {
		testDescrption   string
		input            string
		targetStructName string
		targetLine       int
		ignoreFields     map[string]bool
		expectedImports  []Import
		expectedFields   []Field
	}{
		{
			testDescrption:   "using targetStructName",
			input:            "./example/main.go",
			targetStructName: "Shape2D",
			targetLine:       -1,
			ignoreFields:     nil,
			expectedImports: []Import{
				{Name: "context", Path: "context"},
				{Name: "zap", Path: "go.uber.org/zap"},
			},
			expectedFields: []Field{
				{Name: "logger", Type: "zap.Logger"},
				{Name: "Kind", Type: "ShapeKind"},
				{Name: "X", Type: "int"},
				{Name: "Y", Type: "int"},
				{Name: "Callback", Type: "func(ctx context.Context)"},
				{Name: "Type", Type: "string"},
			},
		},
		{
			testDescrption:   "using targetLine",
			input:            "./example/main.go",
			targetStructName: "",
			targetLine:       17,
			ignoreFields:     nil,
			expectedImports: []Import{
				{Name: "context", Path: "context"},
				{Name: "zap", Path: "go.uber.org/zap"},
			},
			expectedFields: []Field{
				{Name: "logger", Type: "zap.Logger"},
				{Name: "Kind", Type: "ShapeKind"},
				{Name: "X", Type: "int"},
				{Name: "Y", Type: "int"},
				{Name: "Callback", Type: "func(ctx context.Context)"},
				{Name: "Type", Type: "string"},
			},
		},
		{
			testDescrption:   "using targetLine",
			input:            "./example/main.go",
			targetStructName: "",
			targetLine:       17,
			ignoreFields: map[string]bool{
				"logger":   true,
				"Kind":     true,
				"Y":        true,
				"Callback": true,
			},
			expectedImports: []Import{},
			expectedFields: []Field{
				{Name: "X", Type: "int"},
				{Name: "Type", Type: "string"},
			},
		},
	}

	for _, testcase := range testcases {
		testcase := testcase
		t.Run(testcase.testDescrption, func(t *testing.T) {
			t.Parallel()

			actual, err := ParseFile(testcase.input, testcase.targetStructName, testcase.targetLine, testcase.ignoreFields)
			require.NoError(t, err)
			assert.Equal(t, "test", actual.Version)
			assert.Equal(t, "main", actual.PackageName)
			assert.Equal(t, "Shape2D", actual.StructName)
			assert.Equal(t, []string{"//go:build example", "// +build example"}, actual.BuildTags)
			assert.Equal(t, testcase.expectedImports, actual.Imports)
			assert.Equal(t, testcase.expectedFields, actual.Fields)
		})
	}
}

func TestParseFileSkipsBlankField(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "blank.go")
	err := os.WriteFile(path, []byte("package p\n\ntype Shape struct {\n\t_ string\n\tX int\n}\n"), 0o644)
	require.NoError(t, err)

	actual, err := ParseFile(path, "Shape", -1, nil)
	require.NoError(t, err)
	assert.Equal(t, []Field{{Name: "X", Type: "int"}}, actual.Fields)
}

func Test_findImports(t *testing.T) {
	t.Parallel()

	testcases := []struct {
		testDescrption string
		file           *ast.File
		expected       map[string]Import
	}{
		{
			testDescrption: "simple import",
			file: &ast.File{
				Decls: []ast.Decl{
					&ast.GenDecl{
						Tok: token.IMPORT,
						Specs: []ast.Spec{
							&ast.ImportSpec{
								Name: nil,
								Path: &ast.BasicLit{Kind: token.STRING, Value: `"fmt"`},
							},
							&ast.ImportSpec{
								Name: nil,
								Path: &ast.BasicLit{Kind: token.STRING, Value: `"go.uber.org/zap"`},
							},
						},
					},
				},
			},
			expected: map[string]Import{
				"fmt": {Name: "fmt", Path: "fmt"},
				"zap": {Name: "zap", Path: "go.uber.org/zap"},
			},
		},
		{
			testDescrption: "import with name",
			file: &ast.File{
				Decls: []ast.Decl{
					&ast.GenDecl{
						Tok: token.IMPORT,
						Specs: []ast.Spec{
							&ast.ImportSpec{
								Name: nil,
								Path: &ast.BasicLit{Kind: token.STRING, Value: "fmt"},
							},
							&ast.ImportSpec{
								Name: &ast.Ident{Name: "thezap"},
								Path: &ast.BasicLit{Kind: token.STRING, Value: "go.uber.org/zap"},
							},
						},
					},
				},
			},
			expected: map[string]Import{
				"fmt":    {Name: "fmt", Path: "fmt"},
				"thezap": {Name: "thezap", Path: "go.uber.org/zap"},
			},
		},
	}

	for _, testcase := range testcases {
		testcase := testcase
		t.Run(testcase.testDescrption, func(t *testing.T) {
			t.Parallel()

			result := findImports(testcase.file)
			assert.Equal(t, testcase.expected, result)
		})
	}
}
